# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm release
      - uses: actions/upload-artifact@v1.0.0
        name: Upload artifact for mac
        with:
          name: mac
          path: app/release/Smile-darwin-x64/*
      - uses: actions/upload-artifact@v1.0.0
        name: Upload artifact for windows
        with:
          # Artifact name
          name: win32
          # Directory containing files to upload
          path: app/release/Smile-win32-x64/*
